# Platform file for WASI
set(WASI 1)
set(UNIX 1)

# Make program
set(CMAKE_MAKE_PROGRAM "/usr/bin/make" CACHE FILEPATH "make program")

# WASI is a Unix-like environment
set(CMAKE_DL_LIBS "")
set(CMAKE_C_COMPILE_OPTIONS_PIC "")
set(CMAKE_C_COMPILE_OPTIONS_PIE "")
set(CMAKE_SHARED_LIBRARY_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG "")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP "")
set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "")
set(CMAKE_EXE_EXPORTS_C_FLAG "")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".wasm")
set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_SHARED_MODULE_SUFFIX ".wasm")
set(CMAKE_SHARED_MODULE_PREFIX "lib")
set(CMAKE_LINK_LIBRARY_SUFFIX ".a")

# No shared libraries in WASI
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
set(BUILD_SHARED_LIBS OFF)

# Initialize C and CXX compiler rules
include(Platform/UnixPaths)

# Tell CMake how to build for WASI
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT}")
